"""Reverse-Engineered Requirements Document (Markdown + PDF) from site_profile.json + requirements.json."""

from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from app import __version__
from app.core.paths import TEMPLATES_DIR
from app.reports.pdf import html_to_pdf
from app.storage.repository import Repository
from app.storage.schemas import Project, RequirementsDoc, Run, SiteProfile, utcnow

MD_FILE = "exports/requirements.md"
HTML_FILE = "exports/requirements.html"
PDF_FILE = "exports/requirements.pdf"

STATUS_LABEL = {
    "proposed": "Proposed",
    "confirmed": "Confirmed",
    "edited": "Confirmed (edited)",
    "rejected": "Rejected",
}


def _context(project: Project, run: Run, profile: SiteProfile, req: RequirementsDoc) -> dict:
    rules = [r for r in req.rules if r.status != "rejected"]
    return {
        "project": project,
        "run": run,
        "profile": profile,
        "req": req,
        "rules": rules,
        "confirmed": sum(1 for r in rules if r.status in ("confirmed", "edited")),
        "stories_by_role": {
            role: [s for s in req.stories if s.role == role and s.status != "rejected"]
            for role in sorted({s.role for s in req.stories})
        },
        "status_label": STATUS_LABEL,
        "version": __version__,
        "generated": utcnow(),
    }


def render_markdown(project: Project, run: Run, profile: SiteProfile, req: RequirementsDoc) -> str:
    c = _context(project, run, profile, req)
    out = [
        f"# {project.name} — Reverse-Engineered Requirements",
        "",
        f"Source: {project.url} · run `{run.id}` · generated by QA Pilot {__version__} on {c['generated']:%Y-%m-%d}",
        "",
        "## 1. Overview",
        "",
        f"**Domain:** {profile.domain} · {profile.sub_type} (confidence {profile.confidence:.0%}, "
        f"{'Claude analysis' if profile.method == 'ai' else 'offline heuristic'})",
        "",
        profile.summary,
        "",
        "**Roles:** " + ", ".join(profile.roles),
        "",
        "**Modules:** " + ", ".join(profile.modules),
        "",
        "## 2. Data model",
        "",
    ]
    for e in profile.entities:
        out += [f"### {e.name}", "", "| Field | Type | Required | Rules |", "|---|---|---|---|"]
        out += [f"| {f.name} | {f.type} | {'yes' if f.required else ''} | {f.validation} |" for f in e.fields]
        if e.relations:
            out += ["", f"Related to: {', '.join(e.relations)}"]
        out.append("")
    out += ["## 3. User stories", ""]
    for role, stories in c["stories_by_role"].items():
        out += [f"### {role}", ""]
        for s in stories:
            out.append(f"- **{s.id}** {s.story}")
            out += [f"  - {ac}" for ac in s.acceptance_criteria]
        out.append("")
    out += ["## 4. Workflows", ""]
    for w in req.workflows:
        out += [f"### {w.id} {w.name}", "", w.description, ""]
        out += [f"{st.order}. {st.action}" + (f" *(role: {st.role})*" if st.role else "") for st in w.steps]
        if w.states:
            out += [
                "",
                "States: " + " → ".join(w.states),
                "",
                "| From | To | Action | Allowed |",
                "|---|---|---|---|",
            ]
            out += [
                f"| {t.from_state} | {t.to_state} | {t.action} | {'yes' if t.allowed else '**no**'} |"
                for t in w.transitions
            ]
        out.append("")
    out += [
        f"## 5. Business rules ({c['confirmed']} confirmed of {len(c['rules'])})",
        "",
        "| ID | Rule | Condition | Category | Source | Confidence | Status |",
        "|---|---|---|---|---|---|---|",
    ]
    out += [
        f"| {r.id} | {r.statement} | `{r.condition}` | {r.category} | {r.source} | {r.confidence:.0%} | "
        f"{STATUS_LABEL[r.status]} |"
        for r in c["rules"]
    ]
    return "\n".join(out) + "\n"


def export(
    repo: Repository, project: Project, run: Run, profile: SiteProfile, req: RequirementsDoc
) -> dict[str, Path]:
    md = repo.run_path(run, MD_FILE)
    repo.write_text(md, render_markdown(project, run, profile, req))
    env = Environment(loader=FileSystemLoader(TEMPLATES_DIR), autoescape=select_autoescape(["html"]))
    html = env.get_template("requirements.html.j2").render(**_context(project, run, profile, req))
    pdf = html_to_pdf(repo, html, repo.run_path(run, HTML_FILE), repo.run_path(run, PDF_FILE))
    return {"markdown": md, "pdf": pdf}
